// <auto-generated />
namespace HotelBookingApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Migr5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migr5));
        
        string IMigrationMetadata.Id
        {
            get { return "201801281805458_Migr5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
